"""add architecture diagram image url

Revision ID: 27794c47ca9b
Revises: 43f79824e0d5
Create Date: 2026-10-07 10:10:53.523696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27794c47ca9b'
down_revision: Union[str, Sequence[str], None] = '43f79824e0d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('architectures', sa.Column('diagram_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('architectures', 'diagram_image_url')
    # ### end Alembic commands ###
