"""add project team size and technology

Revision ID: 43f79824e0d5
Revises: 9f0c893c948d
Create Date: 2026-10-07 09:59:21.734386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f79824e0d5'
down_revision: Union[str, Sequence[str], None] = '9f0c893c948d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('team_size', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('technology', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'technology')
    op.drop_column('projects', 'team_size')
    # ### end Alembic commands ###
