"""add github integration and commits

Revision ID: aad6484efdc4
Revises: 27794c47ca9b
Create Date: 2026-10-08 17:42:20.240065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad6484efdc4'
down_revision: Union[str, Sequence[str], None] = '27794c47ca9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('repository_owner', sa.String(length=100), nullable=False),
    sa.Column('repository_name', sa.String(length=200), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('webhook_secret', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_integrations_id'), 'github_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_github_integrations_project_id'), 'github_integrations', ['project_id'], unique=False)
    op.create_table('github_commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(length=100), nullable=False),
    sa.Column('commit_message', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('author_email', sa.String(length=200), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('commit_url', sa.Text(), nullable=True),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['github_integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'commit_sha', name='uq_project_commit_sha')
    )
    op.create_index(op.f('ix_github_commits_id'), 'github_commits', ['id'], unique=False)
    op.create_index(op.f('ix_github_commits_integration_id'), 'github_commits', ['integration_id'], unique=False)
    op.create_index(op.f('ix_github_commits_project_id'), 'github_commits', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_commits_project_id'), table_name='github_commits')
    op.drop_index(op.f('ix_github_commits_integration_id'), table_name='github_commits')
    op.drop_index(op.f('ix_github_commits_id'), table_name='github_commits')
    op.drop_table('github_commits')
    op.drop_index(op.f('ix_github_integrations_project_id'), table_name='github_integrations')
    op.drop_index(op.f('ix_github_integrations_id'), table_name='github_integrations')
    op.drop_table('github_integrations')
    # ### end Alembic commands ###
